ALTER TABLE `product`
CHANGE COLUMN `category` `type` VARCHAR(20) NULL DEFAULT NULL ;


ALTER TABLE `product_category`
ADD COLUMN `id` VARCHAR(255) NOT NULL FIRST,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`id`);
;